symbol: "NSE:RITES-EQ"
start_date: "2025-11-01"
end_date: "2025-12-31"

initial_capital: 100000
position_pct: 0.15

buy_th: 0.65
sell_th: 0.35

min_train: 20

atr_period: 14
sl_atr: 1.5
tp_atr: 3.0
